"""empty message

Revision ID: 78b895f00290
Revises: 
Create Date: 2017-09-13 19:08:47.540643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78b895f00290'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grid_cell',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('north_latitude', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('south_latitude', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('east_longitude', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('west_longitude', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('SENTIMENT', 'TOPIC', 'TRAFFIC_JAM', name='ResultTypeEnumType'), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('grid_cell_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grid_cell_id'], ['grid_cell.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    op.drop_table('grid_cell')
    # ### end Alembic commands ###
