"""empty message

Revision ID: f36bdaec5382
Revises: 
Create Date: 2017-09-15 14:25:36.772734

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f36bdaec5382'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=200), nullable=False),
                    sa.Column('slug', sa.String(length=50), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('experiment',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('type',
                              sa.Enum('SENTIMENT', 'TOPIC', 'TRAFFIC_JAM',
                                      name='ResultTypeEnumType'),
                              nullable=False),
                    sa.Column('city_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('grid_cell',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('north_latitude',
                              sa.Numeric(precision=12, scale=8),
                              nullable=False),
                    sa.Column('south_latitude',
                              sa.Numeric(precision=12, scale=8),
                              nullable=False),
                    sa.Column('east_longitude',
                              sa.Numeric(precision=12, scale=8),
                              nullable=False),
                    sa.Column('west_longitude',
                              sa.Numeric(precision=12, scale=8),
                              nullable=False),
                    sa.Column('city_id', sa.Integer(), nullable=False),
                    sa.Column('enabled', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('result',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('updated', sa.DateTime(), nullable=False),
                    sa.Column('value', sa.Text(), nullable=True),
                    sa.Column('grid_cell_id', sa.Integer(), nullable=False),
                    sa.Column('experiment_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['experiment_id'],
                                            ['experiment.id'], ),
                    sa.ForeignKeyConstraint(['grid_cell_id'],
                                            ['grid_cell.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('grid_cellx')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grid_cellx',
                    sa.Column('id', mysql.INTEGER(display_width=11),
                              nullable=False),
                    sa.Column('north_latitude',
                              mysql.DECIMAL(precision=12, scale=8),
                              nullable=False),
                    sa.Column('south_latitude',
                              mysql.DECIMAL(precision=12, scale=8),
                              nullable=False),
                    sa.Column('east_longitude',
                              mysql.DECIMAL(precision=12, scale=8),
                              nullable=False),
                    sa.Column('west_longitude',
                              mysql.DECIMAL(precision=12, scale=8),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_default_charset=u'utf8',
                    mysql_engine=u'InnoDB'
                    )
    op.drop_table('result')
    op.drop_table('grid_cell')
    op.drop_table('experiment')
    op.drop_table('city')
    # ### end Alembic commands ###
